version: 2

project_name: newrelic-cli

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: newrelic-cli
    main: ./cmd/newrelic-cli
    binary: newrelic-cli
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/piekstra/newrelic-cli/internal/version.Version={{.Version}}
      - -X github.com/piekstra/newrelic-cli/internal/version.Commit={{.Commit}}
      - -X github.com/piekstra/newrelic-cli/internal/version.BuildDate={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^Merge pull request"
  groups:
    - title: 'Features'
      regexp: '^feat:'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^fix:'
      order: 1
    - title: 'Other'
      order: 999

release:
  github:
    owner: open-cli-collective
    name: newrelic-cli
